src/web/forms/recuperar_contraseña_form.py
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from flask_wtf import FlaskForm

class RecuperarContraseñaForm(FlaskForm):
    """
    Formulario para la recuperación de contraseña.
    """
    email = StringField('Email', validators=[DataRequired()])
    submit = SubmitField('Recuperar Contraseña')

src/web/forms/usuario_form.py
from wtforms import StringField, PasswordField, SelectField, HiddenField, BooleanField
from wtforms.validators import DataRequired, Length, ValidationError, EqualTo, optional
from src.core.services import usuario_service
from flask_wtf import FlaskForm
import re


class Usuario_Form(FlaskForm):
    id = HiddenField()
    nombre = StringField('Nombre', validators=[DataRequired(), Length(min=2, max=100)])
    apellido = StringField('Apellido', validators=[DataRequired(), Length(min=2, max=100)])
    email = StringField('Email', validators=[DataRequired()])
    contraseña = PasswordField('Contraseña', validators=[DataRequired(), Length(min=8, max=100)])
    id_rol = SelectField('Rol', choices=[], validators=[DataRequired()])
    facultad_id = SelectField('Facultad', choices=[], validators=[optional()])
    posgrado = BooleanField('Posgrado', default=False)
    grado = BooleanField('Grado', default=False)
    id_usuario_editado = HiddenField('id_usuario_editado')
    

    def validate_email(form, field):
        id_usuario_editado = form.id_usuario_editado.data
        usuario_repetido = usuario_service.buscar_usuario_email(field.data)
        if usuario_repetido and usuario_repetido.id != id_usuario_editado:
            raise ValidationError('El email ya está registrado por otro usuario.')


    def validate_contraseña(form, field):
        password = field.data
        if (not re.search("[a-z]", password) or
            not re.search("[A-Z]", password) or
            not re.search("[0-9]", password) or
            not re.search("[!@#$%^&*(),.?\":{}|<>_]", password)):
            raise ValidationError(
                'La contraseña debe tener al menos una letra minúscula, una letra mayúscula, un número, '
                'un carácter especial y un mínimo de 8 caracteres.'
            )

src/web/controllers/usuario_controller.py
from flask import Blueprint, render_template, request, redirect, flash, url_for
from src.core.services import usuario_service, facultades as facultades_service
from src.web.handlers.permisos import check
from src.web.forms import Usuario_Form, Nueva_Contraseña_Form, RecuperarContraseñaForm

usuario_bp = Blueprint("usuarios", __name__, url_prefix="/usuarios")


@usuario_bp.get("/")
@check("usuarios_listar")
def listar():
    pagina = request.args.get('pagina', 1, type=int)
    roles = usuario_service.listar_roles()
    roles = [rol for rol in roles if rol.nombre != "presidencia_jefe"]
    usuarios = usuario_service.listar_usuarios(pagina)
    valores_actuales = {
        'nombre': request.args.get('nombre'),
        'email': request.args.get('email'),
        'rol': request.args.get('rol'),
        'sort': request.args.get('sort'),
        'order': request.args.get('order')
    }
    return render_template("usuarios/listar_usuarios.html", usuarios=usuarios, roles=roles, actuales=valores_actuales)

@usuario_bp.route("/crear", methods=['GET', 'POST'])
@check("usuarios_crear")
def crear_usuario():
    '''
    Crea un usuario.
    
    Returns:
        render_template: La plantilla de crear usuario.
    '''
    formulario = Usuario_Form()
    roles = usuario_service.listar_roles()
    facultades = facultades_service.listar_facultades()
    formulario.id_rol.choices = [("", "Seleccione un rol")] + [(rol.id, rol.nombre) for rol in roles if rol.nombre != "alumno" and rol.nombre != "presidencia_jefe"]
    formulario.facultad_id.choices = [("", "Seleccione una facultad")] + [(facultad.id, facultad.nombre) for facultad in facultades]
    if formulario.validate_on_submit():
        usuario_service.crear_usuario(formulario)
        return redirect("/usuarios")
    return render_template("usuarios/crear_usuario.html", formulario=formulario)

@usuario_bp.get("detalle/<int:id_usuario>")
@check("usuarios_detalle")
def ver_detalle_usuario(id_usuario:int):
    usuario = usuario_service.buscar_usuario(id_usuario)
    roles = usuario_service.listar_roles()
    facultades = facultades_service.listar_facultades()
    formulario = Usuario_Form(obj=usuario)
    formulario.id_rol.choices = [(rol.id, rol.nombre) for rol in roles]
    formulario.facultad_id.choices = [(facultad.id, facultad.nombre) for facultad in facultades]
    return render_template("usuarios/detalle_usuario.html", formulario=formulario, usuario=usuario)


@usuario_bp.route("/editar/<int:id_usuario>", methods=['POST'])
@check("usuarios_editar")   
def editar_usuario(id_usuario:int):
    usuario = usuario_service.buscar_usuario(id_usuario)
    facultades = facultades_service.listar_facultades()
    formulario_usuario = Usuario_Form(obj=usuario, id_usuario_editado=id_usuario)
    formulario_usuario.facultad_id.choices = [(facultad.id, facultad.nombre) for facultad in facultades]
    formulario_usuario.posgrado.data = usuario.posgrado
    formulario_usuario.grado.data = usuario.grado
    formulario_contraseña = Nueva_Contraseña_Form()
    return render_template("usuarios/editar_usuario.html", formulario_usuario=formulario_usuario, formulario_contraseña=formulario_contraseña , usuario=usuario)

@usuario_bp.route("/actualizar/<int:id_usuario>", methods=['POST'])
@check("usuarios_editar")
def actualizar_usuario(id_usuario:int):
    usuario = usuario_service.buscar_usuario(id_usuario)
    roles = usuario_service.listar_roles()
    formulario_usuario = Usuario_Form(obj=usuario, id_usuario_editado=id_usuario)
    if usuario.facultad_id != None:
        facultades = facultades_service.listar_facultades()
        formulario_usuario.facultad_id.choices = [(facultad.id, facultad.nombre) for facultad in facultades]
    formulario_usuario.id_rol.choices = [(rol.id, rol.nombre) for rol in roles]
    formulario_contraseña = Nueva_Contraseña_Form(request.form)

    if formulario_usuario.validate_on_submit() and formulario_contraseña.validate_on_submit():
        formulario_usuario.populate_obj(usuario)
        usuario_service.editar_usuario(usuario, formulario_contraseña.nueva_contraseña.data)
    else:
        return render_template("usuarios/editar_usuario.html", formulario_usuario=formulario_usuario, formulario_contraseña=formulario_contraseña , usuario=usuario)
    return redirect("/")


@usuario_bp.post("/eliminar/<int:id_usuario>")
@check("usuarios_eliminar")
def eliminar_usuario(id_usuario:int):
    '''
    Elimina un usuario.
    
    Args:
        id_usuario (int): El id del usuario a eliminar.
        
    Returns:
        redirect: Redirige a la lista de usuarios.
    '''
    usuario_service.eliminar_usuario(id_usuario)
    return redirect("/usuarios")

@usuario_bp.post("/reactivar/<int:id_usuario>")
@check("usuarios_eliminar")
def reactivar_usuario(id_usuario:int):
    '''
    Reactiva un usuario.
    
    Args:
        id_usuario (int): El id del usuario a reactivar.
        
    Returns:
        redirect: Redirige a la lista de usuarios.
    '''
    usuario_service.reactivar_usuario(id_usuario)
    return redirect("/usuarios")

@usuario_bp.get("/recuperar")
def recuperar_contraseña():
    """
    Muestra el formulario para recuperar la contraseña.
    """
    formulario = RecuperarContraseñaForm()
    return render_template("usuarios/recuperar_contraseña.html", formulario=formulario)

@usuario_bp.post("/recuperar")
def procesar_recuperacion():
    """
    Procesa la solicitud de recuperación de contraseña.
    """
    formulario = RecuperarContraseñaForm()
    if formulario.validate_on_submit():
        user = usuario_service.recuperar_contraseña(formulario) 
        if user:
            return redirect(url_for("auth.login"))
        else:
            flash("El correo no está registrado en nuestro sistema.", "danger")
    return render_template("auth/recuperar_contraseña.html", formulario=formulario)

src/web/templates/usuarios/crear_usuario.html
{% extends "layout.html" %}
{% block title %}Crear Usuario{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<div class="container mt-5">
    
    <form method="POST" class="container-fluid full-height d-flex justify-content-center align-items-center" style="max-width: 500px; max-height: 750px; overflow: hidden;">
        {{ formulario.csrf_token }}
        <div class="container my-5">
            
            <div class="mb-3">
                {{ formulario.nombre.label }}{{ formulario.nombre(class="form-control") }}
                {% if formulario.errors %}
                    {% for error in formulario.nombre.errors %}
                        <div class="text-danger">{{ formulario.errors[0] }}
                            <span style="color: red;">{{ error }}</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="mb-3">
                {{ formulario.apellido.label }}{{ formulario.apellido(class="form-control") }}
                {% if formulario.errors %}
                    {% for error in formulario.apellido.errors %}
                        <div class="text-danger">{{ formulario.errors[0] }}
                            <span style="color: red;">{{ error }}</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            
            <div class="mb-3">
                {{ formulario.email.label }}{{ formulario.email(class="form-control") }}
                {% if formulario.errors %}
                    {% for error in formulario.email.errors %}
                        <div class="text-danger">{{ formulario.errors[0] }}
                            <span style="color: red;">{{ error }}</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="mb-3">
                {{ formulario.contraseña.label }}{{ formulario.contraseña(class="form-control") }}
                {% if formulario.errors %}
                    <div class="text-danger">{{ formulario.errors[0] }}</div>
                {% endif %}
                {% for error in formulario.contraseña.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>

            <div class="mb-3">
                {{ formulario.id_rol.label }}{{ formulario.id_rol(class="form-select", id="id_rol") }}
                {% if formulario.id_rol.errors %}
                    <div class="text-danger">{{ formulario.id_rol.errors[0] }}</div>
                {% endif %}
            </div>

            <div class="mb-3" id="facultad_id" style="display: none;">
                {{ formulario.facultad_id.label }}{{ formulario.facultad_id(class="form-select", id="facultad_id") }}
                {% if formulario.id_rol.errors %}
                    <div class="text-danger">{{ formulario.id_rol.errors[0] }}</div>
                {% endif %}
            </div>
            
            <div class="mb-3" id="grado-container" style="display: none;">
                <label for="grado-checkbox" class="form-label">¿Es de grado?</label>
                <input type="checkbox" id="grado-checkbox" name="grado" value="true" class="form-check-input">
            </div>
            <div class="mb-3" id="posgrado-container" style="display: none;">
                <label for="posgrado-checkbox" class="form-label">¿Es de posgrado?</label>
                <input type="checkbox" id="posgrado-checkbox" name="posgrado" value="true" class="form-check-input">
            </div>


            <button type="submit" class="btn btn-primary my-3">Crear</button>
        </div>
    </form>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const rolSelector = document.getElementById("id_rol");
        const facultadSelector = document.getElementById("facultad_id");
        const posgradoContainer = document.getElementById("posgrado-container");
        const gradoContainer = document.getElementById("grado-container");

        // Escuchar cambios en el selector de roles
        rolSelector.addEventListener("change", function() {
            if (rolSelector.value == 3) {
                // Mostrar el checkbox si el rol es "punto_focal"
                posgradoContainer.style.display = "block";
                gradoContainer.style.display = "block";
                facultadSelector.style.display = "block";
            } else {
                // Ocultar el checkbox para otros roles
                posgradoContainer.style.display = "none";
                gradoContainer.style.display = "none";
                facultadSelector.style.display = "none";
            }
        });
    });
</script>
{% endblock %}

src/web/templates/usuarios/detalle_usuario.html
{% extends "layout.html" %}
{% block title %}Detalle Usuario{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <form method="POST" action={{ url_for('usuarios.editar_usuario', id_usuario=usuario.id) }} class="container-fluid full-height d-flex justify-content-center align-items-center" style="max-width: 500px; max-height: 750px; overflow: hidden;">
        {{ formulario.csrf_token }}
        <div class="container my-5">

            <div class="mb-3">
                {{ formulario.nombre.label }}{{ formulario.nombre(class="form-control", readonly=True) }}
            </div>

            <div class="mb-3">
                {{ formulario.apellido.label }}{{ formulario.apellido(class="form-control", readonly=True) }}
            </div>

            <div class="mb-3">
                {{ formulario.email.label }}{{ formulario.email(class="form-control", readonly=True) }}
            </div>

            <div class="mb-3">
                {{ formulario.id_rol.label }}{{ formulario.id_rol(class="form-control", disabled=True) }}
            </div>

            {% if check_permiso(session, "punto_focal") %}
                <div class="mb-3">
                    {{ formulario.facultad_id.label }}{{ formulario.facultad_id(class="form-control", disabled=True) }}
                </div>
                <div class="mb-3">
                    {{ formulario.posgrado.label }}{{ formulario.posgrado(class="checkbox", disabled=True) }}
                </div>
                <div class="mb-3">
                    {{ formulario.grado.label }}{{ formulario.grado(class="checkbox", disabled=True) }}
                </div>
            {% endif %}



            {% if check_permiso(session, 'admin') or usuario.id == get_id_sesion(session) %}
                <button type="submit" class="btn btn-primary">Editar</button>
            {% endif %} 
                     
        </div>
    </form>
</div>
{% endblock %}

src/web/templates/usuarios/editar_usuario.html
{% extends "layout.html" %}
{% block title %}Editar Usuario{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <form method="POST" action={{ url_for('usuarios.actualizar_usuario', id_usuario=usuario.id) }} onsubmit="return confirmarEliminacion();" class="container-fluid full-height d-flex justify-content-center align-items-center" style="max-width: 500px; max-height: 750px; overflow: hidden;">
        {{ formulario_usuario.csrf_token }}
        {{ formulario_contraseña.csrf_token }}
        
        <div class="container my-5">
            
            {% if check_permiso(session, "admin") or check_permiso(session, "gestor") or check_permiso(session, "punto_focal") %}
                <div class="mb-3">
                    {{ formulario_usuario.nombre.label }}{{ formulario_usuario.nombre(class="form-control") }}
                    {% if formulario_usuario.errors %}
                        {% for error in formulario_usuario.nombre.errors %}
                            <div class="text-danger">{{ formulario_usuario.errors[0] }}
                                <span style="color: red;">{{ error }}</span>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="mb-3">
                    {{ formulario_usuario.apellido.label }}{{ formulario_usuario.apellido(class="form-control") }}
                    {% if formulario_usuario.errors %}
                        {% for error in formulario_usuario.apellido.errors %}
                            <div class="text-danger">{{ formulario_usuario.errors[0] }}
                                <span style="color: red;">{{ error }}</span>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                
                <div class="mb-3">
                    {{ formulario_usuario.email.label }}{{ formulario_usuario.email(class="form-control") }}
                    {% if formulario_usuario.errors %}
                        {% for error in formulario_usuario.email.errors %}
                            <div class="text-danger">{{ formulario_usuario.errors[0] }}
                                <span style="color: red;">{{ error }}</span>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endif %}
            {% if check_permiso(session, "punto_focal") %}
                <div class="mb-3">
                    {{ formulario_usuario.facultad_id.label }}{{ formulario_usuario.facultad_id(class="form-control") }}
                    {% if formulario_usuario.errors %}
                        {% for error in formulario_usuario.facultad_id.errors %}
                            <div class="text-danger">{{ formulario_usuario.errors[0] }}
                                <span style="color: red;">{{ error }}</span>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="mb-3">
                    {{ formulario_usuario.posgrado.label }}{{ formulario_usuario.posgrado(class="checkbox", checked=formulario_usuario.posgrado.data) }}
                </div>
                <div class="mb-3">
                    {{ formulario_usuario.grado.label }}{{ formulario_usuario.grado(class="checkbox", checked=formulario_usuario.grado.data) }}
                </div>
            {% endif %}

            {% if usuario.id == get_id_sesion(session) %}
                <div class="mb-3">
                    {{ formulario_contraseña.nueva_contraseña.label }}{{ formulario_contraseña.nueva_contraseña(class="form-control") }}
                    {% if formulario_contraseña.errors %}
                        {% for error in formulario_contraseña.nueva_contraseña.errors %}
                            <div class="text-danger">{{ formulario_contraseña.errors[0] }}
                                <span style="color: red;">{{ error }}</span>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                
                <div class="mb-3">
                    {{ formulario_contraseña.confirmar_contraseña.label }}{{ formulario_contraseña.confirmar_contraseña(class="form-control") }}
                    {% if formulario_contraseña.errors %}
                        {% for error in formulario_contraseña.confirmar_contraseña.errors %}
                            <div class="text-danger">{{ formulario_contraseña.errors[0] }}
                                <span style="color: red;">{{ error }}</span>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endif %}

            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </form>
</div>
<script>
    function confirmarEliminacion() {
        return confirm("¿Estás seguro de que deseas editar este usuario?");
    }
</script>
{% endblock %}

src/web/templates/usuarios/listar_usuarios.html
{% extends "layout.html" %}
{% block title %}Crear Usuario{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<div class="container mt-3">
    <a href={{ url_for('usuarios.crear_usuario') }} class="btn btn-success mt-3 shadow">+ Nuevo Usuario</a>
    <div class="row my-5">
        <form action="{{ url_for('usuarios.listar') }}" method="GET" class="col-9">
            <div class="row">
                
                <div class="col-3">
                    <label for="nombre" class="form-label">nombre</label>
                    <input type="text" id="nombre" name="nombre" class="form-control shadow" placeholder="Ingresa el nombre para filtrar" {%if actuales.nombre%}value="{{ actuales.nombre }}"{%endif%}>
                </div>
                
                <div class="col-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="text" id="email" name="email" class="form-control shadow" placeholder="Ingresa el email para filtrar" {%if actuales.email%}value="{{ actuales.email }}"{%endif%}>
                </div>
            
                <div class="col-3">
                    <label for="rol" class="form-label">Rol</label>
                    <select id="rol" name="rol" class="form-select shadow">
                        <option value="">Selecciona un rol</option>
                        {% for rol in roles %}
                            <option value="{{ rol.id }}" {% if actuales.rol == rol.id|string %}selected{% endif %}>{{ rol.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>
            
                <div class="col-1"></div>
                <button type="submit" class="btn btn-primary col-1 ms-center shadow">Filtrar</button>
                <div class="col-1"></div>
            </div>
        </form>
        <form action="{{ url_for('usuarios.listar') }}" method="GET" class="row col-3">
            <a href={{ url_for('usuarios.listar') }} class="btn btn-secondary col-4 shadow">Borrar Filtros</a>
        </form>
    </div>

    <table class="table table-striped table-responsive">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>
                    Email
                    <a class="btn p-0" href="{{ url_for('usuarios.listar', sort='email', order='asc', email=actuales.email, nombre=actuales.nombre, rol=actuales.rol) }}">&#9650;</a>
                    <a class="btn p-0" href="{{ url_for('usuarios.listar', sort='email', order='desc', email=actuales.email, nombre=actuales.nombre, rol=actuales.rol) }}">&#9660;</a>
                </th>
                <th>Rol</th>
                <th>
                    Fecha de Creacion
                    <a class="btn p-0" href="{{ url_for('usuarios.listar', sort='creacion', order='asc', email=actuales.email, nombre=actuales.nombre, rol=actuales.rol) }}">&#9650;</a>
                    <a class="btn p-0" href="{{ url_for('usuarios.listar', sort='creacion', order='desc', email=actuales.email, nombre=actuales.nombre, rol=actuales.rol) }}">&#9660;</a>
                </th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>

            {% for usuario in usuarios %}
                <tr>
                    <td>{{ usuario.id }}</td>
                    <td>{{ usuario.nombre }}</td>
                    <td>{{ usuario.apellido }}</td>
                    <td>{{ usuario.email }}</td>
                    <td>{{ usuario.rol.nombre }}</td>
                    <td>{{ usuario.creacion.strftime("%Y-%m-%d") }}</td>
                    <td>{{ usuario.estado.value }}<td>
                        <a href={{ url_for('usuarios.ver_detalle_usuario', id_usuario=usuario.id) }} class="btn btn-primary">Detalle</a>
                        {% if check_permiso(session, 'usuarios_eliminar') %}
                            {% if usuario.estado.value == "activo" %}
                                <form action="{{ url_for('usuarios.eliminar_usuario', id_usuario=usuario.id) }}" method="POST" style="display:inline;" onsubmit="return confirmarEliminacion();">
                                    <button type="submit" class="btn btn-danger">Eliminar</button>
                                    <input id="csrf_token" name="csrf_token" type="hidden" value="{{ csrf_token() }}" />
                                </form>
                            {% else %}

                                <form action="{{ url_for('usuarios.reactivar_usuario', id_usuario=usuario.id) }}" method="POST" style="display:inline;" onsubmit="return confirmarEliminacion();">
                                    <button type="submit" class="btn btn-success">Reactivar</button>
                                    <input id="csrf_token" name="csrf_token" type="hidden" value="{{ csrf_token() }}" />
                                </form>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <br>
    <nav aria-label="Page navigation example shadow">
        <ul class="pagination justify-content-center">
            {% if usuarios.has_prev %}
                <li class="page-item">
                    <a type="submit" href="{{ url_for('usuarios.listar', pagina=usuarios.prev_num, sort=actuales.sort, order=actuales.order, email=actuales.email, nombre=actuales.nombre, rol=actuales.rol) }}" class="page-link"><span aria-hidden="true">&laquo; Anterior</span></a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo; Anterior</span>
                </li>
            {% endif %}
    
            {% for page_num in range(1, usuarios.pages + 1) %}
                {% if page_num == usuarios.page %}
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">{{ page_num }}</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('usuarios.listar', pagina=page_num, sort=actuales.sort, order=actuales.order, email=actuales.email, nombre=actuales.nombre, rol=actuales.rol) }}">{{ page_num }}</a>
                    </li>
                {% endif %} 
            {% endfor %}
    
            {% if usuarios.has_next %}
                <li class="page-item">
                    <a type="submit" href="{{ url_for('usuarios.listar', pagina=usuarios.next_num, sort=actuales.sort, order=actuales.order, email=actuales.email, nombre=actuales.nombre, rol=actuales.rol) }}" class="page-link"><span aria-hidden="true">Siguiente &laquo;</span></a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Siguiente &raquo;</span>
                </li>
            {% endif %}
        </ul>
    </nav>
    

</div>
<script>
    function confirmarEliminacion() {
        return confirm("¿Estás seguro de que deseas eliminar este usuario?");
    }
</script>
{% endblock %}

src/web/templates/usuarios/recuperar_contraseña.html
{% extends "layout.html" %}
{% block title %}Recuperar Contraseña{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<div class="d-flex justify-content-center align-items-center" style="height: 600px;">
    <div class="card shadow p-4" style="width: 30rem;">
        <div class="card-body">
            <h5 class="card-title text-center mb-4">Recuperar Contraseña</h5>
            <form action="{{ url_for('usuarios.procesar_recuperacion') }}" method="POST">
                {{ formulario.csrf_token }}
                <div class="mb-3">
                    {{ formulario.email.label }}{{ formulario.email(class="form-control") }}
                    {% if formulario.errors %}
                        <div class="text-danger">{{ formulario.errors[0] }}</div>
                    {% endif %}
                </div>
                <button type="submit" class="btn btn-primary">Recuperar Contraseña</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}