src/web/forms/carrera_form.py
from wtforms import StringField, SelectField, HiddenField
from wtforms.validators import DataRequired, Length, ValidationError
from flask_wtf import FlaskForm
import re


class CarreraForm(FlaskForm):
    id = HiddenField()
    nombre = StringField('Nombre', validators=[DataRequired(), Length(min=2, max=100)])
    facultad_id = SelectField('Facultad de la que depende', choices=[], validators=[DataRequired()])
    tipo_carrera_id = SelectField('Tipo de carrera', choices=[], validators=[DataRequired()])
    

    def validate_nombre(self, field):
        from src.core.services import carreras as carreras_service
        facultad_id = self.facultad_id.data
        tipo_carrera_id = self.tipo_carrera_id.data
        carrera_repetida = carreras_service.get_carrera_by_nombre_facultad(field.data, tipo_carrera_id, facultad_id)
        if carrera_repetida and carrera_repetida.id != self.id.data:
            raise ValidationError('Esta carrera ya existe.')

src/web/controllers/carreras.py
from flask import Blueprint, flash, redirect, request, render_template, url_for
from src.core.services import facultades as facultades_service
from src.core.services import carreras as carreras_service
from src.core.services import asignaturas as asignaturas_service
from src.web.forms import CarreraForm
from src.web.handlers.permisos import check


carreras_bp = Blueprint("carreras", __name__, url_prefix="/carreras")

#-----Visualizar-----
@carreras_bp.get('/<int:carrera_id>')
@check("carreras_detalle")
def visualizar(carrera_id):
    """Detalle de la carrera con id carrera_id.

    Returns:
        flask.templating.render_template: Plantilla HTML con el detalle de la carrera con id carrera_id.
    """
    
    carrera = carreras_service.get_carrera_by_id(carrera_id)
    if carrera is None:
        flash("La carrera no existe o ha sido eliminada.", "error")
        return redirect(url_for("facultades.listar"))
    return render_template("carreras/visualizar.html", carrera=carrera, asignaturas=carrera.asignaturas)

#-----Crear-----
@carreras_bp.route("/crear", methods=['GET', 'POST'])
@check("carreras_crear")
def crear():
    """Crea una Carrera.

    Returns:
        flask.templating.render_template: Plantilla para crear una Carrera.
    """

    formulario = CarreraForm()

    facultades = facultades_service.get_all_facultades()
    formulario.facultad_id.choices =  [("", "Seleccione una facultad")] + [(facultad.id, facultad.nombre) for facultad in facultades]

    tipos_carrera = carreras_service.get_tipos_carrera()
    formulario.tipo_carrera_id.choices = [("", "Seleccione un tipo de carrera")] + [(tipo_carrera.id, tipo_carrera.nombre) for tipo_carrera in tipos_carrera]
    
    if formulario.validate_on_submit():
        carrera = carreras_service.crear_carrera_web(formulario)
        return redirect(url_for("carreras.listado_asignar_asignaturas", carrera_id = carrera.id))
    return render_template("carreras/crear.html", formulario=formulario)

#-----Editar-----
@carreras_bp.route("/editar/<int:carrera_id>", methods=['GET', 'POST'])
@check("carreras_editar")
def editar(carrera_id):
    """Edita una Asignatura.

    Returns:
        flask.templating.render_template: Plantilla para editar una Asignatura.
    """
    carrera = carreras_service.get_carrera_by_id(carrera_id)
    formulario = CarreraForm(obj=carrera)

    facultades = facultades_service.get_all_facultades()
    formulario.facultad_id.choices =  [("", "Seleccione una facultad")] + [(facultad.id, facultad.nombre) for facultad in facultades]

    tipos_carrera = carreras_service.get_tipos_carrera()
    formulario.tipo_carrera_id.choices = [("", "Seleccione un tipo de carrera")] + [(tipo_carrera.id, tipo_carrera.nombre) for tipo_carrera in tipos_carrera]
    
    if formulario.validate_on_submit():
        carrera = carreras_service.editar_carrera_web(carrera_id,formulario)
        return redirect(url_for("carreras.visualizar", carrera_id = carrera.id))
    return render_template("carreras/editar.html", formulario=formulario, carrera=carrera)

#-----Eliminar-----
@carreras_bp.post("/<int:carrera_id>/eliminar")
@check("carreras_eliminar")
def eliminar(carrera_id):
    """Elimina una Carrera.

    Returns:
        flask.templating.render_template: Visualizacion de facultad de origen.
    """

    previous_url = request.referrer

    carrera = carreras_service.get_carrera_by_id(carrera_id)
    pudo = carreras_service.delete_carrera(carrera_id)
    if pudo:
        flash('La carrera se ha eliminado correctamente', 'success')
    else:
        flash('No se pudo eliminar la carrera', 'error')

    return redirect(previous_url or url_for("facultades.visualizar", facultad_id = carrera.facultad_id))

#-----Asignar asignatura a carreras-----
@carreras_bp.get("/asignar_asignaturas/<int:carrera_id>")
@check("carreras_editar")
def listado_asignar_asignaturas(carrera_id):
    """Renderiza el listado de asignaturas para asignar.

    Returns:
        flask.templating.render_template: Plantilla asignar la carrera a asignaturas.
    """
    carrera = carreras_service.get_carrera_by_id(carrera_id)
    search = request.args.get("search", None)
    search = search.strip().lower() if search else None
    facultad_id = request.args.get("facultad", None)
    try:
        facultad_id = int(facultad_id)
    except (TypeError, ValueError):
        facultad_id = None

    if not (search or facultad_id):
        asignaturas = []
    else:
        asignaturas = asignaturas_service.get_asignaturas(nombre=search, facultad_id=facultad_id, carrera_id=carrera_id)

    facultades = facultades_service.get_all_facultades()
    return render_template("carreras/asignatura_carrera.html", facultades=facultades, asignaturas=asignaturas, search=search, facultad_id=facultad_id, carrera=carrera)

@carreras_bp.get("/asignar_carreras/<int:carrera_id>/<int:asignatura_id>")
@check("carreras_editar")
def asignar_asignatura(carrera_id, asignatura_id):
    """Relaciona una carrera con una materia.

    Returns:
        flask.templating.render_template: Plantilla asignar la carrera a asignaturas.
    """

    previous_url = request.referrer

    pudo = asignaturas_service.relacionar_asignatura_carrera(asignatura_id, carrera_id)
    if pudo:
        flash('La asignatura se ha asignado a la carrera correctamente', 'success')
    else:
        flash('No se pudo asignar la asignatura', 'error')

    return redirect(previous_url or url_for("carreras.listado_asignar_asignaturas", carrera_id=carrera_id))

@carreras_bp.post("/desasignar_carreras/<int:carrera_id>/<int:asignatura_id>")
@check("carreras_editar")
def desasignar_asignatura(carrera_id, asignatura_id):
    """Desrelaciona una carrera con una materia.

    Returns:
        flask.templating.render_template: Plantilla HTML con el detalle de la carrera con id carrera_id.
    """

    previous_url = request.referrer

    pudo = asignaturas_service.desrelacionar_asignatura_carrera(asignatura_id, carrera_id)
    if pudo:
        flash('La asignatura se ha desasignado a la carrera correctamente', 'success')
    else:
        flash('No se pudo desasignar la asignatura', 'error')

    return redirect(previous_url or url_for("carreras.visualizar", carrera_id = carrera_id))

src/web/templates/carreras/asignatura_carrera.html
{% extends "layout.html" %}

{% block title %}Asignar {{ carrera.nombre }} a asignaturas{% endblock %}

{% block content %}
    <div class="container-lg">
        <div class="row align-items-center">
            <div class="col">
                <h1 class="m-0">Asignar {{ carrera.nombre }} a asignaturas</h1>
            </div>
        </div>
        
        <div class="row align-items-center my-3 py-3 border-bottom border-top">
            <div class="col col-md-4">
                <label for="search" class="form-label">Buscar por nombre:</label>
                <div class="input-group">
                    <span class="input-group-text" id="search-search">
                        <i class="bi bi-search"></i>
                    </span>
                    <input type="text" id="search" name="search" class="form-control" placeholder="Ingresar nombre"
                           value="{{ search or '' }}">
                </div>
                <label for="search" class="form-label">Buscar por facultad en la que se cursa:</label>
                <select class="form-select" id="facultad" name="facultad">
                    <option value="">Seleccione una facultad</option>
                    {% for facultad in facultades %}
                        <option {{ facultad_id == facultad.id and "selected" or "" }}
                                value="{{ facultad.id }}">{{ facultad.nombre }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="table-responsive">
            <div class="col">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col" class="text-center">Facultad</th>
                        <th scope="col" class="text-center">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for asignatura in asignaturas %}
                        <tr>
                            <th scope="row" class="align-middle">{{ asignatura.nombre }}</th>
                            <td class="text-center align-middle">{{ asignatura.facultad.nombre }}</td>
                            <td class="text-center align-middle">
                                <div class="btn-group">
                                    <a href="{{ url_for("carreras.asignar_asignatura", carrera_id=carrera.id, asignatura_id=asignatura.id, search=search, facultad_id=facultad_id) }}" class="btn btn-success" data-bs-toggle="tooltip" data-bs-title="Asignar"><i class="bi-plus-square-fill"></i></a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col text-center">
                <a class="btn btn-secondary me-2" href="{{ url_for("carreras.visualizar", carrera_id = carrera.id) }}" role="button">Volver</a>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
            const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));

            const search = document.getElementById("search");
            const facultad = document.getElementById("facultad");
            const change_filters = () => {
                const url = URL.parse(window.location.href);
                const current_url = url.toString();
                const params = url.searchParams;
                if (!params.has("search") || (params.get("search") !== search.value)) {
                    params.set("search", search.value);
                }
                if (!params.has("facultad") || (params.get("facultad") !== facultad.value)) {
                    params.set("facultad", facultad.value);
                }
                if (current_url !== url.toString()) {
                    window.location.href = url.toString();
                }
            };
            search.addEventListener("change", change_filters);
            facultad.addEventListener("change", change_filters);
        });
    </script>
{% endblock %}

src/web/templates/carreras/crear.html
{% extends "layout.html" %}
{% block title %}Crear Carrera{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row align-items-center">
        <div class="col">
            <h1 class="m-0">Nueva carrera</h1>
        </div>
    </div>
    <form method="POST" class="container-fluid full-height d-flex justify-content-center align-items-center" style="max-width: 500px; max-height: 750px; overflow: hidden;">
        {{ formulario.csrf_token }}
        <div class="container my-5">
            
            <div class="mb-3">
                {{ formulario.nombre.label }}{{ formulario.nombre(class="form-control") }}
                {% if formulario.errors %}
                    {% for error in formulario.nombre.errors %}
                        <div class="text-danger">{{ formulario.errors[0] }}
                            <span style="color: red;">{{ error }}</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="mb-3">
                {{ formulario.facultad_id.label }}{{ formulario.facultad_id(class="form-select") }}
                {% if formulario.facultad_id.errors %}
                    <div class="text-danger">{{ formulario.facultad_id.errors[0] }}</div>
                {% endif %}
            </div>

            <div class="mb-3">
                {{ formulario.tipo_carrera_id.label }}{{ formulario.tipo_carrera_id(class="form-select") }}
                {% if formulario.tipo_carrera_id.errors %}
                    <div class="text-danger">{{ formulario.tipo_carrera_id.errors[0] }}</div>
                {% endif %}
            </div>

            <button type="submit" class="btn btn-primary my-3">Crear</button>
        </div>
    </form>
</div>
{% endblock %}

src/web/templates/carreras/editar.html
{% extends "layout.html" %}
{% block title %}Editar Carrera{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row align-items-center">
        <div class="col">
            <h1 class="m-0">Editar {{ carrera.nombre }}</h1>
        </div>
    </div>
    <form method="POST" class="container-fluid full-height d-flex justify-content-center align-items-center" style="max-width: 500px; max-height: 750px; overflow: hidden;">
        {{ formulario.csrf_token }}
        <div class="container my-5">
            
            <div class="mb-3">
                {{ formulario.nombre.label }}{{ formulario.nombre(class="form-control") }}
                {% if formulario.errors %}
                    {% for error in formulario.nombre.errors %}
                        <div class="text-danger">{{ formulario.errors[0] }}
                            <span style="color: red;">{{ error }}</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="mb-3">
                {{ formulario.facultad_id.label }}{{ formulario.facultad_id(class="form-select") }}
                {% if formulario.facultad_id.errors %}
                    <div class="text-danger">{{ formulario.facultad_id.errors[0] }}</div>
                {% endif %}
            </div>

            <div class="mb-3">
                {{ formulario.tipo_carrera_id.label }}{{ formulario.tipo_carrera_id(class="form-select") }}
                {% if formulario.tipo_carrera_id.errors %}
                    <div class="text-danger">{{ formulario.tipo_carrera_id.errors[0] }}</div>
                {% endif %}
            </div>

            <a href="{{ url_for("carreras.visualizar", carrera_id = carrera.id) }}" class="btn btn-secondary me-2">Cancelar</a>
            <button type="submit" class="btn btn-primary my-3">Confirmar cambios</button>
        </div>
    </form>
</div>
{% endblock %}

src/web/templates/carreras/visualizar.html
{% extends "layout.html" %}

{% block title %}Detalles de Carrera{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="m-0">Datos de Carrera <strong>{{ carrera.nombre }}</strong></h1>
            </div>
        </div>
        <div class="row justify-content-center my-3 py-3 border-bottom border-top">
            <div class="col-6">
                <table class="table table-striped">
                    <tbody>
                    <tr>
                        <th scope="row" class="text-end">Nombre:</th>
                        <td class="text-start">{{ carrera.nombre }}</td>
                    </tr>
                    <tr>
                        <th scope="row" class="text-end">Tipo de carrera:</th>
                        <td class="text-start">{{ carrera.tipo_carrera.nombre }}</td>
                    </tr>
                    <tr>
                        <th scope="row" class="text-end">Facultad de la que depende:</th>
                        <td class="text-start">{{ carrera.facultad.nombre }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="container-lg">
        <div class="row align-items-center border-bottom">
            <div class="col">
                <h2 class="m-0">Asignaturas</h2>
            </div>
            {% if check_permiso(session, 'carreras_editar') %}
                <div class="col text-end">
                    <a href="{{ url_for("carreras.listado_asignar_asignaturas", carrera_id = carrera.id) }}" type="button" class="btn btn-success">Asignar asignaturas</a>
                </div>
            {% endif %}
        </div>
        <div class="table-responsive">
            <div class="col">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col" class="text-center">Facultad</th>
                        <th scope="col" class="text-center">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for asignatura in asignaturas %}
                        <tr>
                            <th scope="row" class="align-middle">{{ asignatura.nombre }}</th>
                            <td class="text-center align-middle">{{ asignatura.facultad.nombre }}</td>
                            <td class="text-center align-middle">
                                <div class="btn-group">
                                    <a href="{{ url_for("asignaturas.visualizar", asignatura_id = asignatura.id) }}" class="btn btn-primary" data-bs-toggle="tooltip" data-bs-title="Ver"><i class="bi bi-eye-fill"></i></a>
                                    {% if check_permiso(session, 'carreras_editar') %}
                                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal-{{ asignatura.id }}" data-asignatura-id="{{ asignatura.id }}" data-bs-title="Eliminar">
                                            <i class="bi bi-trash-fill"></i>
                                        </button>
                                        <div class="modal fade" id="confirmDeleteModal-{{ asignatura.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Confirmar eliminación</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                            aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        ¿Estás seguro que deseas desasignar la asignatura {{ asignatura.nombre }}?
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary"
                                                            data-bs-dismiss="modal">Cancelar</button>
                                                        <form method="POST" action="{{ url_for("carreras.desasignar_asignatura", asignatura_id = asignatura.id, carrera_id = carrera.id) }}">
                                                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                                            <button type="submit" class="btn btn-danger">Eliminar</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col text-center">
                <a class="btn btn-secondary me-2" href="{{ url_for("facultades.visualizar", facultad_id = carrera.facultad.id) }}" role="button">{{ carrera.facultad.acronimo }}</a>
                {% if check_permiso(session, 'carreras_editar') %}
                    <a class="btn btn-primary me-2" href="{{ url_for("carreras.editar", carrera_id = carrera.id) }}" role="button">Editar</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}