src/web/forms/programa.py
from flask_wtf import FlaskForm
from wtforms import (StringField, SubmitField, BooleanField)
from wtforms.validators import DataRequired, Length

class ProgramaForm(FlaskForm):
    nombre = StringField('Nombre', validators=[DataRequired(), Length(min=2, max=50)])
    habilitado = BooleanField('Habilitado')
    submit = SubmitField('Guardar')

src/web/controllers/programa_controller.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from src.core.models.postulacion.programa import Programa
from src.core.services import programa_service
from src.web.forms.programa import ProgramaForm
from src.web.handlers.permisos import check

bp = Blueprint('programa', __name__, url_prefix='/programas')  


@bp.get('/crear_programa')
@check('admin')
def crear_programa():
    form = ProgramaForm()
    return render_template('programas/crear_programa.html', form=form)

@bp.post('/guardar_programa')
@check('admin')
def guardar_programa():
    form = ProgramaForm()
    if form.validate_on_submit():
        nombre = form.nombre.data
        habilitado = form.habilitado.data
        if not nombre:
            flash('El nombre es requerido', 'danger')
            return redirect(url_for('programa.crear_programa'))
        programa_service.crear_programa(nombre, habilitado)
        return redirect(url_for('programa.listar_programas'))
    flash('Error al guardar el programa', 'danger')
    return render_template('programas/crear_programa.html', form=form)

@bp.get('/listar_programas')
@check('admin')
def listar_programas():
    programas = programa_service.listar_programas()
    return render_template('programas/listar_programas.html', programas=programas)

@bp.get('/editar_programa/<int:id>')
@check('admin')
def editar_programa(id):
    programa = programa_service.get_programa_by_id(id)
    form = ProgramaForm(obj=programa)
    return render_template('programas/editar_programa.html', form=form, id=id)

@bp.post('/actualizar_programa/<int:id>')
@check('admin')
def actualizar_programa(id):
    form = ProgramaForm()
    if form.validate_on_submit():
        nombre = form.nombre.data
        habilitado = form.habilitado.data
        if not nombre:
            flash('El nombre es requerido', 'danger')
            return redirect(url_for('programa.editar_programa', id=id))
        programa_service.actualizar_programa(id, nombre, habilitado)
        return redirect(url_for('programa.listar_programas'))
    flash('Error al actualizar el programa', 'danger')
    return redirect(url_for('programa.editar_programa', id=id))

@bp.post('/eliminar_programa/<int:id>')
@check('admin')
def eliminar_programa(id):
    programa_service.eliminar_programa(id)
    return redirect(url_for('programa.listar_programas'))

@bp.get('/cambiar_estado_programa/<int:id>')
@check('admin')
def cambiar_estado(id):
    programa = programa_service.get_programa_by_id(id)
    programa.habilitado = not programa.habilitado
    programa_service.actualizar_programa(programa.id, programa.nombre, programa.habilitado)
    flash('Estado actualizado correctamente', 'success')
    return redirect(url_for('programa.listar_programas'))

    

src/web/templates/programas/crear_programa.html
{% extends "layout.html" %}
{% block title %}Crear Programas{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row align-items-center">
        <div class="col">
            <h1 class="m-0">Crear Programa</h1>
        </div>
    </div>
    <form action="{{ url_for('programa.guardar_programa') }}" method="POST" class="container-fluid full-height d-flex justify-content-center align-items-center" style="max-width: 500px; max-height: 750px; overflow: hidden;">
        {{ form.csrf_token }}
        <div class="container my-5">
            
            <div class="mb-3">
                {{ form.nombre.label }}{{ form.nombre(class="form-control") }}
                {% if form.errors %}
                    {% for error in form.nombre.errors %}
                        <div class="text-danger">{{ form.errors[0] }}
                            <span style="color: red;">{{ error }}</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="mb-3 form-check">
                {{ form.habilitado.label(class="form-check-label") }}
                {{ form.habilitado(class="form-check-input") }}
                {% if form.errors %}
                    {% for error in form.habilitado.errors %}
                        <div class="text-danger">{{ form.errors[0] }}
                            <span style="color: red;">{{ error }}</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <button type="submit" class="btn btn-primary my-3">Crear</button>
        </div>
    </form>
</div>
{% endblock %}

src/web/templates/programas/editar_programa.html
{% extends "layout.html" %}
{% block title %}Crear Programas{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row align-items-center">
        <div class="col">
            <h1 class="m-0">Editar Programa</h1>
        </div>
    </div>
    <form action="{{ url_for('programa.actualizar_programa', id=id) }}" method="POST" class="container-fluid full-height d-flex justify-content-center align-items-center" style="max-width: 500px; max-height: 750px; overflow: hidden;">
        {{ form.csrf_token }}
        <div class="container my-5">
            
            <div class="mb-3">
                {{ form.nombre.label }}{{ form.nombre(class="form-control") }}
                {% if form.errors %}
                    {% for error in form.nombre.errors %}
                        <div class="text-danger">{{ form.errors[0] }}
                            <span style="color: red;">{{ error }}</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="mb-3 form-check">
                {{ form.habilitado.label(class="form-check-label") }}
                {{ form.habilitado(class="form-check-input") }}
                {% if form.errors %}
                    {% for error in form.habilitado.errors %}
                        <div class="text-danger">{{ form.errors[0] }}
                            <span style="color: red;">{{ error }}</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <button type="submit" class="btn btn-primary my-3">Actualizar</button>
        </div>
    </form>
</div>
{% endblock %}

src/web/templates/programas/listar_programas.html
{% extends "layout.html" %}
{% block title %}Listar Programas{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<div class="container py-5"> <!-- Agregué un contenedor con padding adicional -->
    <h1 class="display-5 text-center mb-4" >Programas</h1>
    <hr class="mb-4">
    <div class="d-flex justify-content-center mb-3">
        <a href="{{ url_for('programa.crear_programa') }}" class="btn btn-success btn-custom">Crear Programa</a>
    </div>
    
    <div class="table-responsive shadow-sm">
        <table class="table table-bordered table-hover table-striped align-middle">
            <thead class="table-light">
                <tr>
                    <th>Nombre</th>
                    <th>Estado</th>
                    <th>Fecha de carga</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% if not programas %}
                    <tr>
                        <td class="text-center font-medium" colspan="3">No se encontraron programas</td>
                    </tr>
                {% endif %}
                {% for programa in programas %}
                <tr class="border-b border-gray-200 py-2">
                    <td>{{ programa.nombre }}</td>
                    <td>{{ "Habilitado" if programa.habilitado else "Deshabilitado" }}</td>
                    <td>{{ programa.creacion.strftime("%d-%m-%Y") }}</td>
                    <td>
                        {% if programa.habilitado %}
                            <a href="{{ url_for('programa.cambiar_estado', id=programa.id) }}" class="btn btn-warning btn-sm">Deshabilitar</a>
                        {% else %}
                            <a href="{{ url_for('programa.cambiar_estado', id=programa.id) }}" class="btn btn-success btn-sm">Habilitar</a>
                        {% endif %}
                        <a href="{{ url_for('programa.editar_programa', id=programa.id) }}" class="btn btn-primary btn-sm">Editar</a>
                        <!-- Botón para rechazar -->
                        <button type="button" class="btn btn-danger btn-sm" data-id="{{ programa.id }}" data-bs-toggle="modal" data-bs-target="#rejectModal-{{ programa.id }}">
                            Eliminar
                        </button>
                    </td>
                </tr>
                <!-- Modal de Rechazar -->
                <div class="modal fade" id="rejectModal-{{ programa.id }}" tabindex="-1" aria-labelledby="rejectModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <form action="{{ url_for('programa.eliminar_programa', id=programa.id) }}" method="POST">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <div class="modal-header">
                                    <h5 class="modal-title text-danger" id="rejectModalLabel">Eliminar programa</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body text-center">
                                    <p class="mb-0">¿Está seguro que desea eliminar este programa?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Cancelar</button>
                                    <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}