src/web/controllers/facultades.py
from flask import Blueprint, flash, redirect, request, render_template, url_for, session
from src.core.services import facultades as facultades_service
from src.core.services import carreras as carreras_service
from src.core.services import asignaturas as asignaturas_service
from src.core.services import usuario_service as usuarios_service
from src.web.forms.facultad_form import FacultadForm
from src.web.handlers.permisos import check
from src.web.handlers.auth import get_usuario_actual


facultades_bp = Blueprint("facultades", __name__, url_prefix="/facultades")

#-----Listar-----
@facultades_bp.get('/')
@check("facultades_listar")
def listar():
    """Lista todas las facultades.

    Returns:
        flask.templating.render_template: Plantilla HTML con la lista de facultades.
    """

    query = request.args

    nombre = query.get('nombre', None)
    
    facultades = facultades_service.listar_facultades(nombre=nombre)
    return render_template("facultades/listar.html", facultades=facultades, nombre=nombre)

#-----Visualizar-----
@facultades_bp.get('/<int:facultad_id>')
@check("facultades_detalle")
def visualizar(facultad_id):
    """Detalle de la facultad con id facultad_id.

    Returns:
        flask.templating.render_template: Plantilla HTML con el detalle de la facultad con id facultad_id.
    """
    
    query = request.args

    nombre_carrera = query.get('nombre_carrera', None)
    tipo_carrera_id = query.get('tipo_carrera_id', None)
    try:
        tipo_carrera_id = int(tipo_carrera_id)
    except (TypeError, ValueError):
        tipo_carrera_id = None

    carreras = carreras_service.get_carreras_filtradas(facultad_id=facultad_id, nombre=nombre_carrera, tipo_carrera_id=tipo_carrera_id)

    tipos_carrera = carreras_service.get_tipos_carrera()
    
    facultad = facultades_service.get_facultad_by_id(facultad_id=facultad_id)
    if facultad is None:
        flash("La facultad solicitada no existe o ha sido eliminada.", "error")
        return redirect(url_for("facultades.listar"))

    nombre_asignatura = query.get('nombre_asignatura', None)
    pagina_asignatura = request.args.get('pagina_asignatura', 1, type=int)

    asignaturas = asignaturas_service.get_asignaturas_cursadas_por_carreras(carreras_service.get_carreras_by_facultad(facultad_id), nombre=nombre_asignatura, pagina=pagina_asignatura)

    puntos_focales = usuarios_service.get_puntos_focales_by_facultad(facultad_id)

    return render_template("facultades/visualizar.html", facultad=facultad, 
                           carreras=carreras, nombre_carrera=nombre_carrera, tipo_carrera_id=tipo_carrera_id, tipos_carrera=tipos_carrera,
                           asignaturas=asignaturas, nombre_asignatura=nombre_asignatura, pagina_asignatura=pagina_asignatura,
                           puntos_focales=puntos_focales)

@facultades_bp.route("/mifacultad", methods=['GET'])
@check("punto_focal")
def mi_facultad():
    return redirect(url_for("facultades.visualizar", facultad_id = get_usuario_actual(session).facultad_id))


# -----Crear Facultad-----
@facultades_bp.route("/crear", methods=['GET', 'POST'])
@check("facultades_crear")
def crear():
    """Crea una Facultad.

    Returns:
        flask.templating.render_template: Plantilla para crear una Facultad.
    """

    formulario = FacultadForm()

    if formulario.validate_on_submit():
        facultad = facultades_service.crear_facultad_web(formulario)
        return redirect(url_for("facultades.visualizar", facultad_id=facultad.id))

    return render_template("facultades/crear.html", formulario=formulario)

# ----- Editar -----
@facultades_bp.route("/editar/<int:facultad_id>", methods=['GET', 'POST'])
@check("facultades_editar")
def editar(facultad_id):
    """Edita una Facultad.

    Returns:
        flask.templating.render_template: Plantilla para editar una Facultad.
    """
    # Aquí `facultad_id` ya es un argumento entero validado por Flask
    facultad = facultades_service.get_facultad_by_id(facultad_id)
    if not facultad:
        flash("La facultad solicitada no existe o ha sido eliminada.", "error")
        return redirect(url_for("facultades.listar"))

    formulario = FacultadForm(obj=facultad)

    if formulario.validate_on_submit():
        facultades_service.editar_facultad_web(facultad_id, formulario)
        return redirect(url_for("facultades.visualizar", facultad_id=facultad_id))
    
    return render_template("facultades/editar.html", formulario=formulario, facultad=facultad)


# ----- Eliminar -----
@facultades_bp.post("/<int:facultad_id>/eliminar")
@check("facultades_eliminar")
def eliminar(facultad_id):
    """Elimina una Facultad.

    Returns:
        flask.templating.render_template: Visualización del listado de facultades.
    """
    previous_url = request.referrer

    facultad = facultades_service.get_facultad_by_id(facultad_id)
    if not facultad:
        flash("La facultad solicitada no existe o ha sido eliminada.", "error")
        return redirect(url_for("facultades.listar"))
    
    pudo = facultades_service.delete_facultad(facultad_id)
    if pudo:
        flash('La facultad se ha eliminado correctamente', 'success')
    else:
        flash('No se pudo eliminar la facultad', 'error')

    return redirect(previous_url or url_for("facultades.listar"))

src/web/templates/facultades/crear.html
{% extends "layout.html" %}
{% block title %}Crear Facultad{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row align-items-center">
        <div class="col">
            <h1 class="m-0">Nueva facultad</h1>
        </div>
    </div>
    <form method="POST" class="container-fluid full-height d-flex justify-content-center align-items-center" style="max-width: 500px; max-height: 750px; overflow: hidden;">
        {{ formulario.csrf_token }}
        <div class="container my-5">
            
            <div class="mb-3">
                {{ formulario.nombre.label }}{{ formulario.nombre(class="form-control") }}
                {% if formulario.errors %}
                        <div class="text-danger">{{ formulario.nombre.errors[0] }}
                            <span style="color: red;">{{ error }}</span>
                        </div>
                {% endif %}
            </div>

            <div class="mb-3">
                {{ formulario.acronimo.label }}{{ formulario.acronimo(class="form-control") }}
                {% if formulario.errors %}
                        <div class="text-danger">{{ formulario.acronimo.errors[0] }}
                            <span style="color: red;">{{ error }}</span>
                        </div>
                {% endif %}
            </div>

            <button type="submit" class="btn btn-primary my-3">Crear</button>
        </div>
    </form>
</div>
{% endblock %}

src/web/templates/facultades/editar.html
{% extends "layout.html" %}
{% block title %}Editar Facultad{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row align-items-center">
        <div class="col">
            <h1 class="m-0">Editar {{ facultad.nombre }}</h1>
        </div>
    </div>
    <form method="POST" class="container-fluid full-height d-flex justify-content-center align-items-center" style="max-width: 500px; max-height: 750px; overflow: hidden;">
        {{ formulario.csrf_token }}
        <div class="container my-5">
            
            <div class="mb-3">
                {{ formulario.nombre.label }}{{ formulario.nombre(class="form-control") }}
                {% if formulario.errors %}
                        <div class="text-danger">{{ formulario.errors[0] }}
                            <span style="color: red;">{{ error }}</span>
                        </div>
                {% endif %}
            </div>

            <div class="mb-3">
                {{ formulario.acronimo.label }}{{ formulario.acronimo(class="form-control") }}
                {% if formulario.acronimo.errors %}
                    <div class="text-danger">{{ formulario.acronimo.errors[0] }}</div>
                {% endif %}
            </div>


            <a href="{{ url_for("facultades.visualizar", facultad_id = facultad.id) }}" class="btn btn-secondary me-2">Cancelar</a>
            <button type="submit" class="btn btn-primary my-3">Confirmar cambios</button>
        </div>
    </form>
</div>
{% endblock %}

src/web/templates/facultades/listar.html
{% extends "layout.html" %}

{% block title %}Facultades{% endblock %}

{% block content %}
    <div class="container py-5">
        <h1 class="display-5 text-center mb-4">Facultades</h1>
        <hr class="mb-4">
        <div class="col text-end">
            <a href="{{ url_for('facultades.crear') }}" type="button" class="btn btn-success">Nueva Facultad</a>
        </div>

        <div class="table-responsive shadow-sm">
            <table class="table table-bordered table-hover table-striped align-middle">
                <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Acrónimo</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                {% for facultad in facultades %}
                    <tr>
                        <th>{{ facultad.nombre }}</th>
                        <td class="text-center align-middle">{{ facultad.acronimo }}</td>
                        <td class="text-center align-middle">
                            <div class="btn-group">
                                <a href="{{ url_for('facultades.visualizar', facultad_id=facultad.id) }}" class="btn btn-primary" data-bs-toggle="tooltip"
                                   data-bs-title="Ver"><i class="bi bi-eye-fill"></i>
                                </a>
                                <a href="{{ url_for("facultades.editar", facultad_id=facultad.id) }}" class="btn btn-warning" data-bs-toggle="tooltip"
                                   data-bs-title="Editar"><i class="bi bi-pencil-fill"></i></a>
                                <button type="button" class="btn btn-danger" data-bs-title="Eliminar" data-bs-toggle="modal" data-bs-target="#confirmDeleteModalFacultad-{{ facultad.id }}" data-facultad-id="{{ facultad.id }}" data-bs-title="Eliminar">
                                   <i class="bi bi-trash-fill"></i>
                                </button>
                                <div class="modal fade" id="confirmDeleteModalFacultad-{{ facultad.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Confirmar eliminación</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                ¿Estás seguro que deseas eliminar {{ facultad.nombre }}?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"
                                                    data-bs-dismiss="modal">Cancelar</button>
                                                <form method="POST" action="{{ url_for("facultades.eliminar", facultad_id = facultad.id) }}">
                                                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                                    <button type="submit" class="btn btn-danger">Eliminar</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

    <script>
        
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));

        const nombre = document.getElementById("nombre");
        const change_filters = () => {
            const url = URL.parse(window.location.href);
            const current_url = url.toString();
            const params = url.searchParams;
            if (!params.has("nombre") || (params.get("nombre") !== nombre.value)) {
                params.set("nombre", nombre.value);
            }
            if (current_url !== url.toString()) {
                window.location.href = url.toString();
            }
        };
        nombre.addEventListener("change", change_filters);

    </script>
{% endblock %}